### PR TITLE
Add error handler parameter to RegisterStackTraceWriter

### PR DESCRIPTION
**Pull request by nmiyake**
This change is [Reviewable](https://reviewable.io/reviews/palantir/pkg/22)

### CODE REVIEW

**Comment by jonsyu1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/22#-:-KeLtZ8Xs45v-RKEg1aH:bnfp4nl)*

**Comment by jonsyu1** [comment]
Sorry, looks like you conflicted with yourself in #23

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/22#-:-KeLtcV8iI7RT51tno6B:b2bd9xp)*

**Comment by nmiyake** [comment]
Yup wanted to keep the PRs separate for clarity -- fixed conflict.

**Comment by jonsyu1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/22#-:-KeM-1q5rhFQGXt7eGJM:bnfp4nl)*

**Pull request merged**
