### PR TITLE
Add merge package for merging maps.

### PR DESCRIPTION
**Pull request by jamesross3**
This change is [Reviewable](https://reviewable.io/reviews/palantir/pkg/157)

### CODE REVIEW

**Comment by jamesross3** [comment]
@bmoylan @k-simons FYSA

**Comment by jamesross3** [comment]
@nmiyake thanks for pointing out mergo! This meets my use cases which means I don't think we need this change in pkg. Closing.

**Comment by bmoylan** [comment]
Reopening this for @jamesross3 since the repo is currently restricted. From offline convo:
> mergo doesn't handle deep merging of `map[string]interface`s where the key is the same but the values for the key are different types

@jamesross3, can you add and point to a test case which mergo fails to handle?

**Comment by nmiyake** [comment]
___
*[merge/merge.go, line 27 at r4](https://reviewable.io/reviews/palantir/pkg/157#-LesTDbK5OW0bxQ__4oi:-LesTDbK5OW0bxQ__4oj:bfr2ms8) ([raw file](https://github.com/palantir/pkg/blob/80973af93f6cb980e08fb721aa528294486a17b9/merge/merge.go#L27)):*
> ```Go
> // 1. If the values have different types, the value from 'src' is used.
> // 2. If the src value is nil, the entry is absent from the resulting map.
> // 3. If the values are the same type and are structs, the value of dest is persisted (this method is not intended to handle struct value merging).
> ```

This seems strange to me -- in every other case, the value in `src` is used. Why is it that, in the case of structs, the value from `dest` is used instead?

**Comment by jamesross3** [comment]
test comment

**Pull request merged**
