### PR TITLE
Add tlsconfig package

### PR DESCRIPTION
**Pull request by nmiyake**
This change is [Reviewable](https://reviewable.io/reviews/palantir/pkg/26)

### CODE REVIEW

**Comment by jonsyu1** [comment]
Code changes look good, but I'd like to improve our test performance.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tlsconfig/tlsconfig.go, line 106 at r1](https://reviewable.io:443/reviews/palantir/pkg/26#-KeUgBqgamG1RdSi_G03:-KeUgBqgamG1RdSi_G04:bh24hgk) ([raw file](https://github.com/palantir/pkg/blob/371ca0b84dbd331800454d9a9a61cdb0849927b8/tlsconfig/tlsconfig.go#L106)):*
> ```Go
> 	}
> 
> 	for _, currConfigurer := range configs {
> ```

nit: `currConfigurer` is quite a mouthful: how about `cfg` or `configure`?

---

*[tlsconfig/tlsconfig_test.go, line 41 at r1](https://reviewable.io:443/reviews/palantir/pkg/26#-KeUggLl3j87qeDWdGVN:-KeUggLl3j87qeDWdGVO:bqjf43c) ([raw file](https://github.com/palantir/pkg/blob/371ca0b84dbd331800454d9a9a61cdb0849927b8/tlsconfig/tlsconfig_test.go#L41)):*
> ```Go
> 	}
> 
> 	cert1, key1 := newTestKeyPair(1, "test", "localhost")
> ```

Generating and signing cryptographic material is very costly for a unit test. I'd prefer to check in the keypair as a test resource to keep builds fast: especially for testing a lightweight package like `tlsconfig`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/26#-:-KeUh0GRtBgW9FPPjMTX:b-625sgc)*

**Comment by nmiyake** [comment]
Fixed by moving generation code to a file that is run using `go generate` and checking in the currently generated material as part of the commit in `testdata`.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tlsconfig/tlsconfig.go, line 106 at r1](https://reviewable.io:443/reviews/palantir/pkg/26#-KeUgBqgamG1RdSi_G03:-KeV9eTlMCxMGOnwlQhF:b-896fix) ([raw file](https://github.com/palantir/pkg/blob/371ca0b84dbd331800454d9a9a61cdb0849927b8/tlsconfig/tlsconfig.go#L106)):*
<details><summary><i>Previously, jonsyu1 wrote…</i></summary><blockquote>

nit: `currConfigurer` is quite a mouthful: how about `cfg` or `configure`?
</blockquote></details>

Done.

---

*[tlsconfig/tlsconfig_test.go, line 41 at r1](https://reviewable.io:443/reviews/palantir/pkg/26#-KeUggLl3j87qeDWdGVN:-KeVIrufQwpmc8o7gUid:b-896fix) ([raw file](https://github.com/palantir/pkg/blob/371ca0b84dbd331800454d9a9a61cdb0849927b8/tlsconfig/tlsconfig_test.go#L41)):*
<details><summary><i>Previously, jonsyu1 wrote…</i></summary><blockquote>

Generating and signing cryptographic material is very costly for a unit test. I'd prefer to check in the keypair as a test resource to keep builds fast: especially for testing a lightweight package like `tlsconfig`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/26#-:-KeVIuWhj2okQ6xUXTRQ:b-22w6xs)*

**Comment by nmiyake** [comment]
@jonsyu1 lower priority than other things going on, but pinging so this is on your radar (made changes based on initial PR feedback).

**Comment by nmiyake** [comment]
PR has been open for a while, and initial feedback was on tests (which were addressed). Will merge this later today unless I get a NACK.

**Comment by jonsyu1** [comment]
:lgtm:

---

Reviewed 12 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/26#-:-KgLqi38N9K03VBM0hIE:bnfp4nl)*

**Comment by jonsyu1** [comment]
LGTM

**Pull request merged**
