### PR TITLE
Add IntFlag type

### PR DESCRIPTION
**Pull request by bmoylan**
- Use subtests in parse_test.go for test case names

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/pkg/52)

### CODE REVIEW

**Comment by bmoylan** [comment]
@nmiyake for review (I don't have perms to assign directly)

@griechel for SA who needed this a couple weeks ago

**Comment by nmiyake** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/52#-:-KkM2onW77BAanD9NeY-:bnfp4nl)*

**Comment by nmiyake** [comment]
Sorry, turns out that CircleCI builds on PRs was disabled -- I just turned it on. Can you amend the build to retrigger it?

**Comment by bmoylan** [comment]
@nmiyake good to go

**Comment by nmiyake** [comment]
Thanks!

**Pull request merged**
