### PR TITLE
HTTP/Transporter creation 

### PR DESCRIPTION
**Pull request by mahmoudm**
These utility methods allow us to create sanely configured HTTP clients/Transporters. We've hit a variety of issues across our codebase where we misconfigure timeouts, causing a lot of pain in the field. This ensures that the timeouts are properly set.

Specifically, we've seen issues where even if the ClientTimeout is set, you can get stuck infinitely on Dial unless you explicitly set it as well. This is non-obvious and causes a lot of issues.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/pkg/71)

### CODE REVIEW

**Comment by nmiyake** [comment]
Content looks fine -- main request is to add comments to explain what these functions configure (basically want to understand why these functions are nice/what they provide over the built-in defaults) and to choose a package name that is less likely to conflict with built-in packages (and will thus require us to alias the imports).

---

Reviewed 63 of 63 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[http/client.go, line 5 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskLQjlDHcEoS0uADjU:-KskLQjlDHcEoS0uADjV:bs98psp) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/http/client.go#L5)):*
> ```Go
> // license that can be found in the LICENSE file.
> 
> package http
> ```

This package name is very likely to conflict with the built-in `http`. We should use a different name like `httpclient` or `safehttp` or something else of that form.

---

*[http/client.go, line 16 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskLsCX7l5OYChxuddQ:-KskLsCX7l5OYChxuddR:b-2vtezv) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/http/client.go#L16)):*
> ```Go
> )
> 
> func NewHTTPClient(timeout time.Duration, tlsConf *tls.Config) *http.Client {
> ```

Can you provide comments for the functions to describe why they exist/what they configure differently from the built-in packages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/71#-:-KskMHxu3_eKxNyhjsDg:b6pklgw)*

**Comment by nmiyake** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vendor/vendor.json, line 1 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskMlCWjVWA5luZ5vID:-KskMlCWjVWA5luZ5vIE:bi7ssde) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/vendor/vendor.json#L1)):*
> ```JSON
> {
> ```

This project uses `dep` rather than `govendor` -- please use `dep ensure` to update/add vendored dependencies (see https://github.com/golang/dep)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/71)*

**Comment by mahmoudm** [comment]
Review status: 29 of 611 files reviewed at latest revision, 3 unresolved discussions.

---

*[httpclient/client.go, line 16 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskLsCX7l5OYChxuddQ:-KtOr_v42wOD_C-cFHlB:b-896fix) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/httpclient/client.go#L16)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Can you provide comments for the functions to describe why they exist/what they configure differently from the built-in packages?
</blockquote></details>

Done.

---

*[vendor/vendor.json, line 1 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskMlCWjVWA5luZ5vID:-KtOrbJx6R0Jyod2etay:b-896fix) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/vendor/vendor.json#L1)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This project uses `dep` rather than `govendor` -- please use `dep ensure` to update/add vendored dependencies (see https://github.com/golang/dep)
</blockquote></details>

Done.

---

*[http/client.go, line 5 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskLQjlDHcEoS0uADjU:-KsoOtCo6amgulA4zMis:b-896fix) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/http/client.go#L5)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This package name is very likely to conflict with the built-in `http`. We should use a different name like `httpclient` or `safehttp` or something else of that form.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/71)*

**Comment by nmiyake** [comment]
Review status: 29 of 611 files reviewed at latest revision, 2 unresolved discussions.

---

*[httpclient/client.go, line 5 at r1](https://reviewable.io:443/reviews/palantir/pkg/71#-KskLQjlDHcEoS0uADjU:-KtSK7nW5nJi1Jo7Kpe2:b-k61wxx) ([raw file](https://github.com/palantir/pkg/blob/a9e5244dc6e3ab7f734c6638ac8c89d34defc733/httpclient/client.go#L5)):*
<details><summary><i>Previously, mahmoudm (Mahmoud Abdelsalam) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You renamed the parent directory, but package name is still `http` (per `package http` here) -- please update this to `httpclient` as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/71)*

**Comment by nmiyake** [comment]
Request to rename package, but otherwise looks good to me.

---

Review status: 29 of 611 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/71#-:-KtSKSKiVD34lmNLFp4z:be3amza)*

**Comment by nmiyake** [comment]
:lgtm:

---

Reviewed 584 of 591 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/pkg/71#-:-KtSeU-ciCcFf07so7y7:bnfp4nl)*

**Pull request merged**
